// Directory data. Add, remove, or edit members here; the tabs and grid on
// /directory render entirely from this list.

export const teamCategories = [
  "C-Suite",
  "Web Dev Team",
  "Operations",
  "Marketing",
  "Programs",
  "Curriculum",
  "Interns",
] as const;

export type TeamCategory = (typeof teamCategories)[number];

export interface TeamMember {
  id: string;
  name: string;
  /** Omitted for members who should show no position line (e.g. interns). */
  title?: string;
  category: TeamCategory;
  school?: string;
  /** Hierarchy tag (Lead, Manager, Senior Associate, Associate) — shown as a
   * small label above the name when a team has an explicit chain of command. */
  rank?: string;
  /** One entry per paragraph. */
  description?: string[];
}

// Members are listed in hierarchy order within each category — lead first,
// then associates — since the grid renders them in array order.
export const teamMembers: TeamMember[] = [
  // C-Suite
  {
    id: "malhar-sawant",
    name: "Malhar Sawant",
    title: "Founder & Managing Partner",
    category: "C-Suite",
    description: [
      "Malhar founded Bridge Finance Network with a mission to build the next generation of financial talent. With a focus on high finance and financial education, he leads BFN's vision, executes on high-level strategy, and ensures students have access to the best possible experience.",
    ],
  },
  {
    id: "andrew-fu",
    name: "Andrew Fu",
    title: "MD of Internal Affairs & Operations",
    category: "C-Suite",
    description: [
      "Andrew brings three years of experience as a Student Government Treasurer and an intern at Human Resources Administration.",
      "As Co-Founder of BFN, he has been instrumental in building the systems and partnerships that connect 100+ students to financial education and real-world opportunity.",
    ],
  },
  {
    id: "carol-sun",
    name: "Carol Sun",
    title: "MD of Media, Design, & Graphics",
    category: "C-Suite",
    description: [
      "Carol is a DECA International qualifier and grew a simulated investment portfolio from $100K to $560K in just six months.",
      "At BFN, she leads all marketing and media operations, driving the organization's brand presence and growth across every platform.",
    ],
  },
  {
    id: "emily-tai",
    name: "Emily Tai",
    title: "MD of Finance & Accounting",
    category: "C-Suite",
    description: [
      "Emily is a rising senior at Brooklyn Technical High School with a passion for finance and organizational management.",
      "At BFN, she oversees all fundraising and budgeting, ensuring the organization has the financial foundation to grow and serve its members.",
    ],
  },
  {
    id: "sai-karthik",
    name: "Sai Karthik",
    title: "MD of Technology & AI",
    category: "C-Suite",
    description: [
      "Sai is a rising senior at Marquette High School with deep experience in artificial intelligence and technical systems.",
      "At BFN, he leads platform architecture and engineering, building the technical infrastructure that gives students a seamless, powerful experience.",
    ],
  },
  {
    id: "anderson-overkamp",
    name: "Anderson Overkamp",
    title: "MD of Experiential Programs & Development",
    category: "C-Suite",
    description: [
      "Anderson began his finance journey as a self-directed stock market investor and equity researcher, documenting his analysis through his own website and blog.",
      "He brings deep knowledge in equity research and financial writing to help BFN deliver meaningful, real-world learning experiences.",
    ],
  },

  // Web Dev Team
  {
    id: "sashitej-palla",
    name: "Sashitej Palla",
    title: "Vice President, Web Development",
    category: "Web Dev Team",
    school: "Mount Olive High School",
    rank: "Lead",
  },
  {
    id: "kanav-jaitly",
    name: "Kanav Jaitly",
    title: "Web Development Manager",
    category: "Web Dev Team",
    school: "Mount Olive High School",
    rank: "Manager",
  },
  {
    id: "ackshat-tiwari",
    name: "Ackshat Tiwari",
    title: "Senior Associate",
    category: "Web Dev Team",
    school: "Rock Ridge High School",
    rank: "Senior Associate",
  },
  {
    id: "sathvik-shivam",
    name: "Sathvik Shivam",
    title: "Senior Associate",
    category: "Web Dev Team",
    school: "Metea Valley High School",
    rank: "Senior Associate",
  },
  {
    id: "arnav-srivastava",
    name: "Arnav Srivastava",
    title: "Associate",
    category: "Web Dev Team",
    school: "Marquette High School",
    rank: "Associate",
  },

  // Operations
  {
    id: "henry-harvey",
    name: "Henry Harvey",
    title: "Vice President, Operations",
    category: "Operations",
    school: "Rye Country Day School",
    rank: "Lead",
  },
  {
    id: "hrudya-pullalarevu",
    name: "Hrudya Pullalarevu",
    title: "Senior Associate",
    category: "Operations",
    school: "Northville High School",
    rank: "Senior Associate",
  },
  {
    id: "aryan-katakam",
    name: "Aryan Katakam",
    title: "Associate",
    category: "Operations",
    school: "Seminole High School",
    rank: "Associate",
  },

  // Marketing
  {
    id: "jannatul-jami",
    name: "Jannatul Jami",
    title: "Marketing Associate",
    category: "Marketing",
    school: "Baruch College",
  },
  {
    id: "abhiram-ramasahayam",
    name: "Abhiram Ramasahayam",
    title: "Marketing Associate",
    category: "Marketing",
    school: "Leadership Prep Secondary School",
  },
  {
    id: "tanvi-aegyarapu",
    name: "Tanvi Aegyarapu",
    title: "Marketing Associate",
    category: "Marketing",
    school: "Wakeland High School",
  },

  // Programs
  {
    id: "aditya-amarjeet-singh",
    name: "Aditya Amarjeet Singh",
    title: "Programs Associate",
    category: "Programs",
    school: "Allen High School",
  },
  {
    id: "saharsh-bhaskarla",
    name: "Saharsh Bhaskarla",
    title: "Programs Associate",
    category: "Programs",
    school: "Monroe Township High School",
  },
  {
    id: "sahil-mathur",
    name: "Sahil Mathur",
    title: "Programs Associate",
    category: "Programs",
    school: "Monroe Township High School",
  },
  {
    id: "yuvraj-dharmapuri",
    name: "Yuvraj Dharmapuri",
    title: "Programs Associate",
    category: "Programs",
    school: "Monroe Township High School",
  },

  // Curriculum
  {
    id: "sudheeksha-karray",
    name: "Sudheeksha Karray",
    title: "Curriculum Associate",
    category: "Curriculum",
    school: "Lake Washington High School",
  },
  {
    id: "sanat-tibrewal",
    name: "Sanat Tibrewal",
    title: "Curriculum Associate",
    category: "Curriculum",
    school: "Allen High School",
  },
  {
    id: "aneesh-thatta",
    name: "Aneesh Thatta",
    title: "Curriculum Associate",
    category: "Curriculum",
    school: "Lambert High School",
  },
  {
    id: "hardik-laddha",
    name: "Hardik Laddha",
    title: "Curriculum Associate",
    category: "Curriculum",
    school: "John P. Stevens High School",
  },
  {
    id: "hardik-vij",
    name: "Hardik Vij",
    title: "Curriculum Associate",
    category: "Curriculum",
    school: "St. Mary's School",
  },

  // Interns — sorted alphabetically by last name, then first name.
  { id: "abdoulkerim-abdelkerim", name: "Abdoulkerim Abdelkerim", category: "Interns", school: "James Hubert Blake HS" },
  { id: "tanvi-aegyarapu", name: "Tanvi Aegyarapu", category: "Interns", school: "Wakeland High School" },
  { id: "tanya-aegyarapu", name: "Tanya Aegyarapu", category: "Interns", school: "Wakeland High School" },
  { id: "aarush-agarwal", name: "Aarush Agarwal", category: "Interns", school: "Lebanon Trail High School" },
  { id: "kushal-anchuri", name: "Kushal Anchuri", category: "Interns", school: "Lebanon Trail High School" },
  { id: "vinay-annamalai", name: "Vinay Annamalai", category: "Interns", school: "Thomas Edison Charter" },
  { id: "munveer-annavaram", name: "Munveer Annavaram", category: "Interns", school: "Middleton High School" },
  { id: "vidhi-arora", name: "Vidhi Arora", category: "Interns", school: "Spring Dale Senior School" },
  { id: "abhinav-arul", name: "Abhinav Arul", category: "Interns", school: "Montgomery HS" },
  { id: "manav-arun", name: "Manav Arun", category: "Interns", school: "Birla Public School" },
  { id: "motunrayo-ayinde-tukur", name: "Motunrayo Ayinde-Tukur", category: "Interns", school: "University of Lagos" },
  { id: "mubarak-azeez", name: "Mubarak Azeez", category: "Interns", school: "Newark School Data Science HS" },
  { id: "nandika-baddam", name: "Nandika Baddam", category: "Interns", school: "Wakeland High School" },
  { id: "hadi-baig", name: "Hadi Baig", category: "Interns", school: "Aden Bowman Collegiate" },
  { id: "tanay-balabhadruni", name: "Tanay Balabhadruni", category: "Interns", school: "Panther Creek High School" },
  { id: "gurunarayan-balaji", name: "Gurunarayan Balaji", category: "Interns", school: "Middleton High School" },
  { id: "harshi-bandaru", name: "Harshi Bandaru", category: "Interns", school: "Coppell High School" },
  { id: "raga-battu", name: "Raga Battu", category: "Interns", school: "Frisco High School" },
  { id: "ameek-bhalla", name: "Ameek Bhalla", category: "Interns", school: "West Forsyth HS" },
  { id: "dwij-bhargava", name: "Dwij Bhargava", category: "Interns", school: "Liberty High School" },
  { id: "kritika-bhatia", name: "Kritika Bhatia", category: "Interns", school: "Subodh Public School" },
  { id: "simar-bhatia", name: "Simar Bhatia", category: "Interns", school: "Goodley Public School" },
  { id: "varun-bhatia", name: "Varun Bhatia", category: "Interns", school: "Sri Guru Gobind Singh College" },
  { id: "kabir-bhushan", name: "Kabir Bhushan", category: "Interns", school: "Marquette High School" },
  { id: "pavan-binwani", name: "Pavan Binwani", category: "Interns", school: "Frisco Centennial HS" },
  { id: "manasvi-bobade", name: "Manasvi Bobade", category: "Interns", school: "Alliance Academy for Innovation" },
  { id: "vaishnavi-bommireddipalli", name: "Vaishnavi Bommireddipalli", category: "Interns", school: "Central Peel Secondary" },
  { id: "jahnae-brown", name: "Jahnae Brown", category: "Interns", school: "Saunders Trade+Technical HS" },
  { id: "pranav-chadha", name: "Pranav Chadha", category: "Interns", school: "University of Alberta" },
  { id: "abhiraj-chand", name: "Abhiraj Chand", category: "Interns", school: "Rock Hill High School" },
  { id: "vivian-chao", name: "Vivian Chao", category: "Interns", school: "Bridgewater Raritan HS" },
  { id: "manvik-chaudhary", name: "Manvik Chaudhary", category: "Interns", school: "Nashua High School South" },
  { id: "matthew-chen", name: "Matthew Chen", category: "Interns", school: "Plainview Old Bethpage JFK HS" },
  { id: "sophia-chen", name: "Sophia Chen", category: "Interns", school: "Highland Park HS" },
  { id: "shreyas-choudhury", name: "Shreyas Choudhury", category: "Interns", school: "Argyle High School" },
  { id: "janaiah-clark", name: "Janaiah Clark", category: "Interns", school: "Miami Dade Virtual School" },
  { id: "janashia-clark", name: "Janashia Clark", category: "Interns", school: "Miami-Dade Virtual School" },
  { id: "reggie-clark-jr", name: "Reggie Clark Jr.", category: "Interns", school: "Miami-Dade Virtual School" },
  { id: "christian-clarke", name: "Christian Clarke", category: "Interns", school: "Gonzaga College High School" },
  { id: "jordan-currin", name: "Jordan Currin", category: "Interns", school: "Collin College" },
  { id: "swaraj-d", name: "Swaraj D", category: "Interns", school: "Victorious Kidss Educares" },
  { id: "john-d-emic", name: "John D'Emic", category: "Interns", school: "Long Beach High School" },
  { id: "muhammad-haris-daoud", name: "Muhammad Haris Daoud", category: "Interns", school: "International School of Lahore" },
  { id: "akshit-dash", name: "Akshit Dash", category: "Interns", school: "Global Indian International School" },
  { id: "ryan-david", name: "Ryan David", category: "Interns", school: "Monroe Township HS" },
  { id: "charlotte-davidson", name: "Charlotte Davidson", category: "Interns", school: "Miller Place HS" },
  { id: "romir-dedhia", name: "Romir Dedhia", category: "Interns", school: "Bridgewater-Raritan HS" },
  { id: "dhairya-desai", name: "Dhairya Desai", category: "Interns", school: "Cherokee High School" },
  { id: "omkar-desai", name: "Omkar Desai", category: "Interns", school: "Marquette High School" },
  { id: "ruvaneka-desilva", name: "Ruvaneka DeSilva", category: "Interns", school: "Rutgers Prep" },
  { id: "aayush-dhar", name: "Aayush Dhar", category: "Interns", school: "Bridgewater Raritan HS" },
  { id: "khushi-dhotre", name: "Khushi Dhotre", category: "Interns", school: "Livingston High School" },
  { id: "saketh-dintakurti", name: "Saketh Dintakurti", category: "Interns", school: "Monroe Township HS" },
  { id: "sai-raaghav-diwakar", name: "Sai Raaghav Diwakar", category: "Interns", school: "Allen High School" },
  { id: "abhinav-dubey", name: "Abhinav Dubey", category: "Interns", school: "NIT Calicut" },
  { id: "sophia-duong", name: "Sophia Duong", category: "Interns", school: "Frontier STEM Academy" },
  { id: "aradhay-dwivedi", name: "Aradhay Dwivedi", category: "Interns", school: "Sunbeam School Laharatara" },
  { id: "garrett-ewy", name: "Garrett Ewy", category: "Interns", school: "Blue Valley West HS" },
  { id: "andy-fenstermaker", name: "Andy Fenstermaker", category: "Interns", school: "Seymour High School" },
  { id: "anam-fuzail", name: "Anam Fuzail", category: "Interns", school: "South Brunswick High School" },
  { id: "shrija-gaba", name: "Shrija Gaba", category: "Interns", school: "APA" },
  { id: "abhay-gadam", name: "Abhay Gadam", category: "Interns", school: "McNeil High School" },
  { id: "om-garine", name: "Om Garine", category: "Interns", school: "Marquette High School" },
  { id: "ana-gaur", name: "Ana Gaur", category: "Interns", school: "GEMS New Millennium School" },
  { id: "vivan-gheewala", name: "Vivan Gheewala", category: "Interns", school: "Monroe Township HS" },
  { id: "vedant-golan", name: "Vedant Golan", category: "Interns", school: "Birla Divya Jyoti" },
  { id: "sara-govani", name: "Sara Govani", category: "Interns", school: "Piscataway High School" },
  { id: "yena-gu", name: "Yena Gu", category: "Interns", school: "Prepa Tec Eugenio Garza" },
  { id: "aarav-gupta", name: "Aarav Gupta", category: "Interns", school: "Bridgewater Raritan HS" },
  { id: "aarush-gupta", name: "Aarush Gupta", category: "Interns", school: "Prosper Richland HS" },
  { id: "masuda-hairulla", name: "Masuda Hairulla", category: "Interns", school: "Morris Knolls" },
  { id: "kamrul-hassan", name: "Kamrul Hassan", category: "Interns", school: "Fyruz Education Services" },
  { id: "john-heard", name: "John Heard", category: "Interns", school: "Arkansas Connections Academy" },
  { id: "celine-huang", name: "Celine Huang", category: "Interns", school: "Bukit Sion High School" },
  { id: "harden-hyde", name: "Harden Hyde", category: "Interns", school: "UNC Chapel Hill" },
  { id: "dhruv-jain", name: "Dhruv Jain", category: "Interns", school: "Emerson High School" },
  { id: "nitya-jain", name: "Nitya Jain", category: "Interns", school: "Bridgewater-Raritan HS" },
  { id: "ronak-jain", name: "Ronak Jain", category: "Interns", school: "Podar International School" },
  { id: "soham-jain", name: "Soham Jain", category: "Interns", school: "McLean High School" },
  { id: "anish-janapareddi", name: "Anish Janapareddi", category: "Interns", school: "Monroe Township High School" },
  { id: "navya-jha", name: "Navya Jha", category: "Interns", school: "Prosper High School" },
  { id: "ved-jujjavarapu", name: "Ved Jujjavarapu", category: "Interns", school: "Marquette Sr. High School" },
  { id: "neil-kaler", name: "Neil Kaler", category: "Interns", school: "American School of Doha" },
  { id: "abhiram-kanteti", name: "Abhiram Kanteti", category: "Interns", school: "Leadership Prep School" },
  { id: "krishnam-kapila", name: "Krishnam Kapila", category: "Interns", school: "DAV" },
  { id: "sonu-karnati", name: "Sonu Karnati", category: "Interns", school: "Leander High School" },
  { id: "mahathi-karthik", name: "Mahathi Karthik", category: "Interns", school: "Bridgewater-Raritan HS" },
  { id: "siddharth-karthik-nithya", name: "Siddharth Karthik Nithya", category: "Interns", school: "Seminole High School" },
  { id: "harshaa-karthikeyan", name: "Harshaa Karthikeyan", category: "Interns", school: "Tom Glenn High School" },
  { id: "yuvan-katamaneni", name: "Yuvan Katamaneni", category: "Interns", school: "Tomball Memorial HS" },
  { id: "menaj-katta", name: "Menaj Katta", category: "Interns", school: "St. Mark's School" },
  { id: "mikaal-hussain-khan", name: "Mikaal Hussain Khan", category: "Interns", school: "St Mary Catholic Secondary" },
  { id: "shayaan-khan", name: "Shayaan Khan", category: "Interns", school: "Middleton High School" },
  { id: "nischal-konduru", name: "Nischal Konduru", category: "Interns", school: "WW Plainsboro South HS" },
  { id: "keshav-kulshrestha", name: "Keshav Kulshrestha", category: "Interns", school: "Redwood" },
  { id: "mohit-kumar", name: "Mohit Kumar", category: "Interns", school: "University of Delhi" },
  { id: "saanvi-lamba", name: "Saanvi Lamba", category: "Interns", school: "North Brunswick Township HS" },
  { id: "hellen-liu", name: "Hellen Liu", category: "Interns", school: "Great Neck North HS" },
  { id: "wangshu-liu", name: "Wangshu Liu", category: "Interns", school: "Marquette High School" },
  { id: "lucas-lu", name: "Lucas Lu", category: "Interns", school: "Livingston High School" },
  { id: "thristan-lundy", name: "Thristan Lundy", category: "Interns", school: "Abington Senior HS" },
  { id: "xi-luo", name: "Xi Luo", category: "Interns", school: "Francis Lewis High School" },
  { id: "yashika-makam", name: "Yashika Makam", category: "Interns", school: "Richland High School" },
  { id: "julia-malinowski", name: "Julia Malinowski", category: "Interns", school: "LaGuardia High School of Arts" },
  { id: "sriteja-malladi", name: "Sriteja Malladi", category: "Interns", school: "North Brunswick Township HS" },
  { id: "amrit-mann", name: "Amrit Mann", category: "Interns", school: "Hightstown High School" },
  { id: "ubaid-maredia", name: "Ubaid Maredia", category: "Interns", school: "Leander High School" },
  { id: "franchesca-marinez", name: "Franchesca Marinez", category: "Interns", school: "Brooklyn Technical HS" },
  { id: "diego-martinez", name: "Diego Martinez", category: "Interns", school: "American School Foundation Puebla" },
  { id: "sarvesh-masalkar", name: "Sarvesh Masalkar", category: "Interns", school: "Troy High School" },
  { id: "ishani-mazumder", name: "Ishani Mazumder", category: "Interns", school: "Rock Hill High School" },
  { id: "jash-mehta", name: "Jash Mehta", category: "Interns", school: "Dubai American Academy" },
  { id: "nohamin-melesse", name: "Nohamin Melesse", category: "Interns", school: "University of Warsaw" },
  { id: "ishaan-merchant", name: "Ishaan Merchant", category: "Interns", school: "Robbinsville High School" },
  { id: "bavishya-meruva", name: "Bavishya Meruva", category: "Interns", school: "Tom Glenn High School" },
  { id: "robston-milfort", name: "Robston Milfort", category: "Interns", school: "Essex County Newark Tech" },
  { id: "kushagra-mishra", name: "Kushagra Mishra", category: "Interns", school: "Heritage High School" },
  { id: "shivank-mishra", name: "Shivank Mishra", category: "Interns", school: "Dubai International Academy" },
  { id: "aarush-modi", name: "Aarush Modi", category: "Interns", school: "St. Mary CSS" },
  { id: "harshil-mongia", name: "Harshil Mongia", category: "Interns", school: "Delhi University" },
  { id: "oliver-morton", name: "Oliver Morton", category: "Interns", school: "Seton Hall Preparatory" },
  { id: "maximilian-mui", name: "Maximilian Mui", category: "Interns", school: "White Plains Public HS" },
  { id: "keshab-musaddi", name: "Keshab Musaddi", category: "Interns", school: "L.K. Singhania Education Centre" },
  { id: "mohit-nair", name: "Mohit Nair", category: "Interns", school: "Lone Star High School" },
  { id: "suhayb-nasir", name: "Suhayb Nasir", category: "Interns", school: "Sinclair Secondary School" },
  { id: "rygel-ng", name: "Rygel Ng", category: "Interns", school: "Brooklyn Technical HS" },
  { id: "vy-nguyen", name: "Vy Nguyen", category: "Interns", school: "Tran Dai Nghia HS" },
  { id: "shiloh-ninan", name: "Shiloh Ninan", category: "Interns", school: "Birla Public School" },
  { id: "nicole-nyamgarav", name: "Nicole Nyamgarav", category: "Interns", school: "Yorktown High School" },
  { id: "kevin-oneill", name: "Kevin Oneill", category: "Interns", school: "Regis High School" },
  { id: "aybike-oran", name: "Aybike Oran", category: "Interns", school: "Ataturk Anatolian HS" },
  { id: "leo-osorio", name: "Leo Osorio", category: "Interns", school: "UNIS" },
  { id: "gyan-padoli", name: "Gyan Padoli", category: "Interns", school: "Heritage High School" },
  { id: "sahan-pasnuri", name: "Sahan Pasnuri", category: "Interns", school: "Hillsborough High School" },
  { id: "aayog-patel", name: "Aayog Patel", category: "Interns", school: "Hebron High School" },
  { id: "drew-patel", name: "Drew Patel", category: "Interns", school: "North Brunswick Township HS" },
  { id: "jay-patel", name: "Jay Patel", category: "Interns", school: "Burlington Township HS" },
  { id: "krish-patel", name: "Krish Patel", category: "Interns", school: "Wayne County High School" },
  { id: "moksh-patel", name: "Moksh Patel", category: "Interns", school: "South Brunswick High School" },
  { id: "sophia-patel", name: "Sophia Patel", category: "Interns", school: "Parkway Central" },
  { id: "tanay-patel", name: "Tanay Patel", category: "Interns", school: "Monroe Township HS" },
  { id: "yash-patel", name: "Yash Patel", category: "Interns", school: "Hillsborough High School" },
  { id: "monisha-pathi", name: "Monisha Pathi", category: "Interns", school: "Lake Washington HS" },
  { id: "karthik-pavani", name: "Karthik Pavani", category: "Interns", school: "Lebanon Trail High School" },
  { id: "karthik-pesaladinne", name: "Karthik Pesaladinne", category: "Interns", school: "Independence High School" },
  { id: "shloka-reddy-pesaladinne", name: "Shloka Reddy Pesaladinne", category: "Interns", school: "Independence High School" },
  { id: "karsten-pham", name: "Karsten Pham", category: "Interns", school: "Cedar Ridge High School" },
  { id: "besiki-pkhakadze", name: "Besiki Pkhakadze", category: "Interns", school: "Wilfrid Laurier University" },
  { id: "kharishma-prabhu", name: "Kharishma Prabhu", category: "Interns", school: "Tom Glenn High School" },
  { id: "jahnavi-pullela", name: "Jahnavi Pullela", category: "Interns", school: "Canton High School" },
  { id: "akhil-puvvada", name: "Akhil Puvvada", category: "Interns", school: "Round Rock High School" },
  { id: "jivan-puvvada", name: "Jivan Puvvada", category: "Interns", school: "North Brunswick Township High School" },
  { id: "rhea-rachala", name: "Rhea Rachala", category: "Interns", school: "Middleton High School" },
  { id: "keshav-raghunath", name: "Keshav Raghunath", category: "Interns", school: "Middleton High School" },
  { id: "akshita-raj", name: "Akshita Raj", category: "Interns", school: "Sinclair Secondary School" },
  { id: "haresh-rajeshshanmugam", name: "Haresh RajeshShanmugam", category: "Interns", school: "Mira Loma High School" },
  { id: "abhinav-ramakrishnan", name: "Abhinav Ramakrishnan", category: "Interns", school: "Monroe Township High School" },
  { id: "pratham-rao", name: "Pratham Rao", category: "Interns", school: "Monroe Township HS" },
  { id: "darsh-rathod", name: "Darsh Rathod", category: "Interns", school: "The Windsor Boys School" },
  { id: "alexander-richardson", name: "Alexander Richardson", category: "Interns", school: "Alexander Hamilton Senior HS" },
  { id: "sofi-roshe", name: "Sofi Roshe", category: "Interns", school: "Westfield High School" },
  { id: "ayush-sahoo", name: "Ayush Sahoo", category: "Interns", school: "Middleton High School" },
  { id: "dhriti-saireddy", name: "Dhriti Saireddy", category: "Interns", school: "Novi High School" },
  { id: "arjun-sethi", name: "Arjun Sethi", category: "Interns", school: "Prosper High School" },
  { id: "shritan-settipalli", name: "Shritan Settipalli", category: "Interns", school: "Neuqua Valley High School" },
  { id: "kavya-setty", name: "Kavya Setty", category: "Interns", school: "Frisco High School" },
  { id: "moksh-shah", name: "Moksh Shah", category: "Interns", school: "Chatrabhuj Narsee School" },
  { id: "vaishvi-shah", name: "Vaishvi Shah", category: "Interns", school: "Sinclair Secondary School" },
  { id: "aryan-sharma", name: "Aryan Sharma", category: "Interns", school: "Green Hope High School" },
  { id: "ridhwan-sharma", name: "Ridhwan Sharma", category: "Interns", school: "Bridgewater Raritan Regional HS" },
  { id: "smyan-shastri", name: "Smyan Shastri", category: "Interns", school: "Felton Grove High School" },
  { id: "pahul-shelly", name: "Pahul Shelly", category: "Interns", school: "Independence High School" },
  { id: "lavanya-shrivastava", name: "Lavanya Shrivastava", category: "Interns", school: "Sun Valley International" },
  { id: "rishi-simhadri", name: "Rishi Simhadri", category: "Interns", school: "Marquette High School" },
  { id: "armaan-singh", name: "Armaan Singh", category: "Interns", school: "DAV Public School, BRS" },
  { id: "tanisha-singh", name: "Tanisha Singh", category: "Interns", school: "Smt. SBVM" },
  { id: "bhupesh-sinha", name: "Bhupesh Sinha", category: "Interns", school: "Pass Out" },
  { id: "viraj-sonawane", name: "Viraj Sonawane", category: "Interns", school: "Middleton High School" },
  { id: "siri-sure", name: "Siri Sure", category: "Interns", school: "Dwight Global" },
  { id: "niranjana-suresh-preethy", name: "Niranjana Suresh Preethy", category: "Interns", school: "Sinclair Secondary School" },
  { id: "avyay-surubhotla", name: "Avyay Surubhotla", category: "Interns", school: "Hillsborough High School" },
  { id: "daksh-suryadevara", name: "Daksh Suryadevara", category: "Interns", school: "Kingswood Oxford School" },
  { id: "siddharth-talla", name: "Siddharth Talla", category: "Interns", school: "Briar Woods High School" },
  { id: "krupesh-thakkar", name: "Krupesh Thakkar", category: "Interns", school: "North Brunswick Township High School" },
  { id: "revaa-thoom", name: "Revaa Thoom", category: "Interns", school: "Liberty Hill" },
  { id: "johnny-tokarz", name: "Johnny Tokarz", category: "Interns", school: "Seymour High School" },
  { id: "jayden-tong", name: "Jayden Tong", category: "Interns", school: "Cedar Ridge High School" },
  { id: "suraj-tripathy", name: "Suraj Tripathy", category: "Interns", school: "Hillsborough High School" },
  { id: "neel-vadlamani", name: "Neel Vadlamani", category: "Interns", school: "Walter Payton College Prep" },
  { id: "suryansh-varshney", name: "Suryansh Varshney", category: "Interns", school: "TMS" },
  { id: "elijah-varughese", name: "Elijah Varughese", category: "Interns", school: "Northeast High School" },
  { id: "nishan-vense", name: "Nishan Vense", category: "Interns", school: "McNeil High School" },
  { id: "atulya-raj-verma", name: "Atulya Raj Verma", category: "Interns", school: "Univ of Delhi Motilal Nehru" },
  { id: "aarush-vignesh", name: "Aarush Vignesh", category: "Interns", school: "Seminole High School" },
  { id: "smruthi-vongole", name: "Smruthi Vongole", category: "Interns", school: "Elkins High School" },
  { id: "saicharan-vutukuri", name: "Saicharan Vutukuri", category: "Interns", school: "Middleton High School" },
  { id: "chloe-wang", name: "Chloe Wang", category: "Interns", school: "Great Neck South High School" },
  { id: "clayton-wangsanata", name: "Clayton Wangsanata", category: "Interns", school: "Lambert High School" },
  { id: "vaishnavi-yadav", name: "Vaishnavi Yadav", category: "Interns", school: "Vidya Devi Jindal School" },
  { id: "pavit-yaduwanshi", name: "Pavit Yaduwanshi", category: "Interns", school: "Liberty High School" },
  { id: "tarun-yamarthy", name: "Tarun Yamarthy", category: "Interns", school: "North Brunswick Township High School" },
  { id: "junjie-yang", name: "Junjie Yang", category: "Interns", school: "Cedar Ridge High School" },
  { id: "yong-yan-yong", name: "Yong Yan Yong", category: "Interns", school: "Universiti Malaya" },
  { id: "ethan-zann", name: "Ethan Zann", category: "Interns", school: "Grosse Pointe South" },
  { id: "neri-zhunio", name: "Neri Zhunio", category: "Interns", school: "Franklin Towne Charter HS" },
];
